build:
  runs-on: ubuntu-latest
  steps:
    %checkout%
    %install%
    - uses: actions/cache@v2
      id: build-cache
      name: Cache dist
      with:
        path: packages/*/dist
        key: ${{ runner.os }}-dist-14-${{ hashFiles('yarn.lock') }}
    - name: Build dist
      run: yarn build && yarn build:umd
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          packages/*/dist
          packages/react-styles/css


