build:
  runs-on: ubuntu-latest
  steps:
    %checkout%
    %install%
    - uses: actions/cache@v2
      id: build-cache
      name: Load build cache
      with:
        path: |
          '**/dist'
          packages/react-styles/css
        key: ${{ runner.os }}-build-14-${{ hashFiles('yarn.lock') }}
    - name: Build dist
      run: yarn build && yarn build:umd

