- uses: actions/checkout@v2
# Yes, we really want to checkout the PR
- run: printenv
- run: echo $GH_PR_NUM
- run: |
    if [[ -v $GH_PR_NUM ]]; then 
      echo "Checking out PR"
      git fetch origin pull/$GH_PR_NUM/head:tmp
      git checkout tmp
    fi
