demo_app:
  runs-on: ubuntu-latest
  needs: build
  steps:
    %build%
    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Build demo app
      run: yarn build:integration
    - name: Save build folder
      uses: actions/upload-artifact@v2
      with:
        name: demo_app
        if-no-files-found: error
        path: packages/react-docs/demo-app/public

