docs:
  runs-on: ubuntu-latest
  needs: build
  env:
    SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
    SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
  steps:
    %checkout%
    %install%
    - uses: actions/cache@v2
      id: docs-cache
      name: Load webpack cache
      with:
        path: '.cache'
        key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
    - name: Build docs
      run: yarn build:docs
    - name: Save build folder
      uses: actions/upload-artifact@v2
      with:
        name: docs
        if-no-files-found: error
        path: packages/react-docs/public
    - run: node .github/upload-preview.js packages/react-docs/public
      name: Upload docs
      if: always()

