docs:
  runs-on: ubuntu-latest
  needs: build
  env:
    SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
    SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
  steps:
    %checkout%
    %install%
    %dist%
    - uses: actions/cache@v2
      id: docs-cache
      name: Cache webpack
      with:
        path: '.cache'
        key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
    - name: Build docs
      run: yarn build:docs
    - name: Upload docs
      run: node .github/upload-preview.js packages/react-docs/public
      if: always()
    - name: a11y tests
      run: yarn serve & yarn test:a11y
    - name: Upload a11y results
      run: node .github/upload-preview.js packages/react-docs/coverage
      if: always()
