- uses: actions/setup-node@v1
  with:
    node-version: '14'
- uses: actions/cache@v2
  id: yarn-cache
  name: Load npm deps from cache
  with:
    path: |
     '**/node_modules'
     ~/.cache/Cypress
    key: ${{ runner.os }}-yarn-14-${{ hashFiles('yarn.lock') }}
- run: yarn install --frozen-lockfile
  if: steps.yarn-cache.outputs.cache-hit != 'true'

