test_a11y:
  runs-on: ubuntu-latest
  needs: docs
  env:
    SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
    SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
  steps:
    %checkout%
    %install%
    - name: a11y tests
      run: yarn serve & yarn test
    - name: Upload docs
      run: node .github/upload-preview.js public
      if: always()

