test_jest:
  runs-on: ubuntu-latest
  needs: build
  steps:
    %checkout%
    %install%
    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: PF4 Jest Tests
      run: yarn test --maxWorkers=2
