test_integration:
  runs-on: ubuntu-latest
  needs: demo_app
  strategy:
    fail-fast: false
    matrix:
      containers: [1, 2, 3, 4, 5]
  steps:
    %checkout%
    %install%
    %dist%
    - name: Download demo app
      uses: actions/download-artifact@v2
      with:
        name: demo-app
        path: packages/react-integration/demo-app-ts/public
    - name: Sanity
      run: ls packages/react-integration/demo-app-ts
    - name: Cypress tests
      uses: cypress-io/github-action@v2
      with:
        install: false
        start: yarn serve:integration
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 10
        browser: chrome
        record: true
        parallel: true
        group: 'UI - Chrome'
        working-directory: packages/react-integration

