name: release
on:
  push:
    branches:
      - main
jobs:
  %build%
  %lint%
  %test_jest%
  %docs%
  %demo_app%
  %test_integration%
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test_jest, test_integration, build]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_REDALLEN }}
      %checkout%
      %install%
      %dist%
      - name: Avoid Unknown Host for github.com
        run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - name: Deploy to NPM and Github
        run: .github/release.sh

